import { useEffect, useMemo, useRef, useState } from 'react'
import { createWorker } from 'tesseract.js'
import { isSupabaseConfigured, supabase } from './lib/supabaseClient'

const SYSTEM_KEYS = new Set(['id', 'created_at', 'updated_at', 'deleted_at'])
const LABELS = { registry_number: 'Αριθμός Μητρώου', registration_number: 'Αριθμός Μητρώου', registry_no: 'Αριθμός Μητρώου', am: 'Αριθμός Μητρώου', student_number: 'Αριθμός Μητρώου', last_name: 'Επώνυμο', surname: 'Επώνυμο', first_name: 'Όνομα', name: 'Όνομα', full_name: 'Ονοματεπώνυμο', phone: 'Τηλέφωνο', semester: 'Εξάμηνο', group: 'Ομάδα', status: 'Κατάσταση' }
function labelFor(key) { return LABELS[key] || key.replaceAll('_', ' ') }
function valueFor(row, aliases) { const key = Object.keys(row || {}).find((candidate) => aliases.includes(candidate)); return key ? row[key] : '' }

function StudentForm({ row, columns, onCancel, onSave, busy }) {
  const editableColumns = columns.filter((column) => !SYSTEM_KEYS.has(column)); const [draft, setDraft] = useState(() => ({ ...(row || {}) })); useEffect(() => setDraft({ ...(row || {}) }), [row])
  return <form className="data-card" onSubmit={(event) => { event.preventDefault(); onSave(draft) }} style={{ padding: '1rem', marginBottom: '1rem' }}><div className="page-title-row"><div><p className="kicker">{row?.id ? 'Επεξεργασία' : 'Νέα εγγραφή'}</p><h2>{row?.id ? '✏️ Διόρθωση σπουδαστή' : '➕ Νέος σπουδαστής'}</h2><p>Όλα τα διαθέσιμα στοιχεία παραμένουν διορθώσιμα πριν την αποθήκευση.</p></div></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: '0.85rem' }}>{editableColumns.map((column) => <label key={column}>{labelFor(column)}<input value={draft[column] == null ? '' : String(draft[column])} onChange={(event) => setDraft((current) => ({ ...current, [column]: event.target.value }))} /></label>)}</div><div style={{ display: 'flex', gap: '0.65rem', justifyContent: 'flex-end', marginTop: '1rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={onCancel}>Ακύρωση</button><button type="submit" className="primary-button" disabled={busy}>{busy ? 'Αποθήκευση…' : 'Αποθήκευση'}</button></div></form>
}

function normalizeOcrLine(value) { return String(value || '').replace(/[|¦]/g, ' ').replace(/\s+/g, ' ').trim() }
function normalizeRegistryToken(token) { return String(token || '').toUpperCase().replace(/[ΟO]/g, '0').replace(/[ΙIÎ]/g, '1').replace(/[ΖZ]/g, '2').replace(/[ΕE]/g, '3').replace(/[ΑA]/g, '4').replace(/[SΣ]/g, '5').replace(/[GΓ]/g, '6').replace(/[ΤT]/g, '7').replace(/[ΒB]/g, '8').replace(/[qQ]/g, '9').replace(/\D/g, '') }
function cleanName(value) { return normalizeOcrLine(value).replace(/^[\s:;,.\-–—_/\\]+/, '').replace(/\s+/g, ' ').trim() }
function parseOcrLines(lines) {
  const results = []; const seen = new Set(); const blocked = /(ΗΜΕΡ|ΠΑΡΟΥΣ|ΣΠΟΥΔΑΣΤ|ΟΝΟΜΑΤΕΠΩΝ|ΕΠΩΝΥΜ|ΗΜΕΡΟΜΗΝ|ΥΠΟΓΡΑΦ|ΣΧΟΛΗ|ΤΜΗΜΑ|ΕΞΑΜΗΝΟ)/iu
  for (const rawLine of lines) { const line = normalizeOcrLine(rawLine); if (!line || blocked.test(line)) continue; const candidates = [...line.matchAll(/(?:^|\s)([0-9ΟOIΙΖZΕEAΑSΣGΓΤTΒBqQ]{4,8})(?=\s|$)/g)]; let selected = null; for (const candidate of candidates) { const registryNumber = normalizeRegistryToken(candidate[1]); if (registryNumber.length >= 4 && registryNumber.length <= 6) { selected = { candidate, registryNumber }; break } } if (!selected || seen.has(selected.registryNumber)) continue; let fullName = cleanName(line.slice(selected.candidate.index + selected.candidate[0].length)); if (!fullName || !/[A-ZΑ-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]/u.test(fullName)) continue; const parts = fullName.split(/\s+/).filter(Boolean); if (parts.length < 2) continue; if (fullName.length > 100) fullName = fullName.slice(0, 100).trim(); seen.add(selected.registryNumber); results.push({ registryNumber: selected.registryNumber, fullName, lastName: parts[0] || '', firstName: parts.slice(1).join(' ') }) }
  return results
}

async function prepareImage(file) { const bitmap = await createImageBitmap(file); const maxWidth = 2400; const scale = Math.min(1, maxWidth / bitmap.width); const width = Math.max(1, Math.round(bitmap.width * scale)); const height = Math.max(1, Math.round(bitmap.height * scale)); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const context = canvas.getContext('2d', { willReadFrequently: true }); context.drawImage(bitmap, 0, 0, width, height); const image = context.getImageData(0, 0, width, height); const data = image.data; for (let i = 0; i < data.length; i += 4) { const luminance = data[i] * 0.299 + data[i + 1] * 0.587 + data[i + 2] * 0.114; const contrast = Math.max(0, Math.min(255, ((luminance - 128) * 1.35) + 128)); data[i] = contrast; data[i + 1] = contrast; data[i + 2] = contrast }; context.putImageData(image, 0, 0); const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.95)); bitmap.close?.(); if (!blob) throw new Error('Δεν ήταν δυνατή η προετοιμασία της εικόνας.'); return new File([blob], 'attendance-document-ocr.jpg', { type: 'image/jpeg' }) }

function CropEditor({ file, onApply, onSkip, onBack }) {
  const [imageUrl, setImageUrl] = useState('')
  const [corners, setCorners] = useState({ nw: { x: 6, y: 5 }, ne: { x: 94, y: 5 }, se: { x: 94, y: 93 }, sw: { x: 6, y: 93 } })
  const [activeCorner, setActiveCorner] = useState(null)
  const [applying, setApplying] = useState(false)
  const areaRef = useRef(null)
  const dragRef = useRef(null)
  useEffect(() => { const url = URL.createObjectURL(file); setImageUrl(url); return () => URL.revokeObjectURL(url) }, [file])
  function startDrag(event, corner) { event.preventDefault(); event.stopPropagation(); setActiveCorner(corner); event.currentTarget.setPointerCapture?.(event.pointerId); const rect = areaRef.current?.getBoundingClientRect(); if (!rect) return; dragRef.current = { corner, x: event.clientX, y: event.clientY, corners: JSON.parse(JSON.stringify(corners)), rect } }
  function moveCorner(event) { const drag = dragRef.current; if (!drag?.rect) return; const dx = ((event.clientX - drag.x) / drag.rect.width) * 100; const dy = ((event.clientY - drag.y) / drag.rect.height) * 100; const next = JSON.parse(JSON.stringify(drag.corners)); next[drag.corner].x = Math.max(0, Math.min(100, drag.corners[drag.corner].x + dx)); next[drag.corner].y = Math.max(0, Math.min(100, drag.corners[drag.corner].y + dy)); setCorners(next) }
  function stopDrag() { dragRef.current = null }
  async function applyCrop() {
    if (applying) return
    setApplying(true)
    try {
      const bitmap = await createImageBitmap(file)
      const sourceCanvas = document.createElement('canvas'); sourceCanvas.width = bitmap.width; sourceCanvas.height = bitmap.height
      const sourceContext = sourceCanvas.getContext('2d', { willReadFrequently: true }); sourceContext.drawImage(bitmap, 0, 0)
      const source = sourceContext.getImageData(0, 0, bitmap.width, bitmap.height)
      const src = [corners.nw, corners.ne, corners.se, corners.sw].map((p) => ({ x: p.x * bitmap.width / 100, y: p.y * bitmap.height / 100 }))
      const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y)
      let outWidth = Math.max(1, Math.round(Math.max(distance(src[0], src[1]), distance(src[3], src[2]))))
      let outHeight = Math.max(1, Math.round(Math.max(distance(src[0], src[3]), distance(src[1], src[2]))))
      const maxPixels = 3000000; const scale = Math.min(1, Math.sqrt(maxPixels / (outWidth * outHeight))); outWidth = Math.max(1, Math.round(outWidth * scale)); outHeight = Math.max(1, Math.round(outHeight * scale))
      const a = Array.from({ length: 8 }, () => Array(9).fill(0)); const dst = [{ x: 0, y: 0 }, { x: outWidth - 1, y: 0 }, { x: outWidth - 1, y: outHeight - 1 }, { x: 0, y: outHeight - 1 }]
      for (let i = 0; i < 4; i += 1) { const x = dst[i].x; const y = dst[i].y; const u = src[i].x; const v = src[i].y; a[i * 2] = [x, y, 1, 0, 0, 0, -x * u, -y * u, u]; a[i * 2 + 1] = [0, 0, 0, x, y, 1, -x * v, -y * v, v] }
      for (let col = 0; col < 8; col += 1) { let pivot = col; for (let row = col + 1; row < 8; row += 1) if (Math.abs(a[row][col]) > Math.abs(a[pivot][col])) pivot = row; if (Math.abs(a[pivot][col]) < 1e-10) throw new Error('Μη έγκυρη περιοχή crop.'); [a[col], a[pivot]] = [a[pivot], a[col]]; const div = a[col][col]; for (let j = col; j < 9; j += 1) a[col][j] /= div; for (let row = 0; row < 8; row += 1) { if (row === col) continue; const factor = a[row][col]; if (!factor) continue; for (let j = col; j < 9; j += 1) a[row][j] -= factor * a[col][j] } }
      const h = a.map((row) => row[8]).concat(1); const output = new ImageData(outWidth, outHeight); const d = output.data; const s = source.data; const sw = bitmap.width; const sh = bitmap.height
      for (let y = 0; y < outHeight; y += 1) for (let x = 0; x < outWidth; x += 1) { const den = h[6] * x + h[7] * y + 1; const sx = (h[0] * x + h[1] * y + h[2]) / den; const sy = (h[3] * x + h[4] * y + h[5]) / den; const x0 = Math.floor(sx); const y0 = Math.floor(sy); const x1 = Math.min(x0 + 1, sw - 1); const y1 = Math.min(y0 + 1, sh - 1); const tx = sx - x0; const ty = sy - y0; const oi = (y * outWidth + x) * 4; if (x0 < 0 || y0 < 0 || x0 >= sw || y0 >= sh) { d[oi + 3] = 0; continue }; const p00 = (y0 * sw + x0) * 4; const p10 = (y0 * sw + x1) * 4; const p01 = (y1 * sw + x0) * 4; const p11 = (y1 * sw + x1) * 4; for (let c = 0; c < 3; c += 1) d[oi + c] = Math.round((s[p00 + c] * (1 - tx) + s[p10 + c] * tx) * (1 - ty) + (s[p01 + c] * (1 - tx) + s[p11 + c] * tx) * ty); d[oi + 3] = 255 }
      const canvas = document.createElement('canvas'); canvas.width = outWidth; canvas.height = outHeight; canvas.getContext('2d').putImageData(output, 0, 0); const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.96)); bitmap.close?.(); if (!blob) throw new Error('Δεν ήταν δυνατή η δημιουργία του ισιωμένου εγγράφου.'); onApply(new File([blob], 'attendance-perspective-cropped.jpg', { type: 'image/jpeg' }))
    } catch (cropError) {
      setApplying(false)
      throw cropError
    }
  }
  const handleStyle = (corner) => ({ position: 'absolute', left: `${corners[corner].x}%`, top: `${corners[corner].y}%`, width: 30, height: 30, marginLeft: -15, marginTop: -15, borderRadius: '50%', background: '#fff', border: '3px solid #17233b', boxSizing: 'border-box', touchAction: 'none', zIndex: 5, cursor: 'crosshair', boxShadow: '0 1px 6px rgba(0,0,0,0.5)' })
  const activePoint = activeCorner ? corners[activeCorner] : null
  return (
    <div style={{ marginTop: '0.8rem' }}>
      <div className="audit-note">✂️ <strong>1. Επιλογή 4 γωνιών</strong> — μετακίνησε κάθε λευκή γωνία ανεξάρτητα πάνω στη γωνία του χαρτιού. Το μικρό παράθυρο zoom δείχνει μεγεθυμένο το σημείο που χειρίζεσαι.</div>
      <div ref={areaRef} style={{ position: 'relative', marginTop: '0.7rem', width: '100%', overflow: 'hidden', borderRadius: 14, background: '#111', lineHeight: 0, touchAction: 'none' }}>
        <img src={imageUrl} alt="Προεπισκόπηση για crop" style={{ display: 'block', width: '100%', height: 'auto', userSelect: 'none', pointerEvents: 'none' }} />
        {imageUrl && <>
          <div style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.38)', clipPath: `polygon(0 0, 100% 0, 100% 100%, 0 100%)`, pointerEvents: 'none' }} />
          <svg style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', pointerEvents: 'none' }} viewBox="0 0 100 100" preserveAspectRatio="none"><polygon points={`${corners.nw.x},${corners.nw.y} ${corners.ne.x},${corners.ne.y} ${corners.se.x},${corners.se.y} ${corners.sw.x},${corners.sw.y}`} fill="rgba(255,255,255,0.04)" stroke="white" strokeWidth="0.9" vectorEffect="non-scaling-stroke" /></svg>
          {activePoint && <div style={{ position: 'absolute', right: 10, top: 10, width: 104, height: 104, borderRadius: 12, border: '3px solid #fff', backgroundImage: `url(${imageUrl})`, backgroundRepeat: 'no-repeat', backgroundSize: '300% 300%', backgroundPosition: `${activePoint.x}% ${activePoint.y}%`, boxShadow: '0 3px 12px rgba(0,0,0,0.55)', zIndex: 6, overflow: 'hidden', pointerEvents: 'none' }}><div style={{ position: 'absolute', left: '50%', top: '50%', width: 18, height: 18, marginLeft: -9, marginTop: -9, border: '2px solid #fff', borderRadius: '50%', boxShadow: '0 0 0 1px #17233b' }} /><div style={{ position: 'absolute', left: 5, right: 5, bottom: 4, textAlign: 'center', color: '#fff', fontSize: 10, fontWeight: 700, textShadow: '0 1px 3px #000' }}>ZOOM</div></div>}
          {Object.keys(corners).map((corner) => <span key={corner} aria-label={`Γωνία ${corner}`} onPointerDown={(event) => startDrag(event, corner)} onPointerMove={moveCorner} onPointerUp={() => { stopDrag(); setActiveCorner(null) }} onPointerCancel={() => { stopDrag(); setActiveCorner(null) }} style={handleStyle(corner)} />)}
        </>}
      </div>
      <div style={{ display: 'flex', gap: '0.6rem', justifyContent: 'space-between', marginTop: '0.8rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={onBack} disabled={applying}>↩️ Πίσω</button><div style={{ display: 'flex', gap: '0.6rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={onSkip} disabled={applying}>Χωρίς crop</button><button type="button" className="primary-button" onClick={applyCrop} disabled={applying}>{applying ? '⏳ Κόψιμο & ίσιωμα…' : '✂️ 2. Crop & ίσιωμα'}</button></div></div>
      <div className="audit-note" style={{ marginTop: '0.7rem' }}>Με το <strong>Crop & ίσιωμα</strong> δημιουργείται νέο πραγματικό αρχείο εικόνας: κρατά μόνο τις 4 γωνίες, διορθώνει την προοπτική και μετά εμφανίζει ξεχωριστά το βήμα <strong>3. Στείλε για OCR</strong>.</div>
    </div>
  )
}

function OcrImport({ existingRows, columns, onImport, onClose }) {
  const [file, setFile] = useState(null); const [previewUrl, setPreviewUrl] = useState(''); const [ocrText, setOcrText] = useState(''); const [items, setItems] = useState([]); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(''); const [error, setError] = useState(''); const [cameraOpen, setCameraOpen] = useState(false); const [cameraError, setCameraError] = useState(''); const [needsCrop, setNeedsCrop] = useState(false)
  const videoRef = useRef(null); const streamRef = useRef(null); const galleryInputRef = useRef(null)
  useEffect(() => () => { if (previewUrl) URL.revokeObjectURL(previewUrl); if (streamRef.current) streamRef.current.getTracks().forEach((track) => track.stop()) }, [previewUrl])
  const registryColumn = columns.find((key) => ['registry_number', 'registration_number', 'registry_no', 'am', 'student_number', 'arithmos_mitroou'].includes(key)); const nameColumn = columns.find((key) => ['full_name', 'name', 'student_name', 'onomateponymo'].includes(key)); const lastNameColumn = columns.find((key) => ['last_name', 'surname', 'eponymo'].includes(key)); const firstNameColumn = columns.find((key) => ['first_name', 'onoma'].includes(key))
  function stopCamera() { if (streamRef.current) { streamRef.current.getTracks().forEach((track) => track.stop()); streamRef.current = null }; if (videoRef.current) videoRef.current.srcObject = null; setCameraOpen(false) }
  async function openCamera() { setCameraError(''); if (!navigator.mediaDevices?.getUserMedia) { setCameraError('Η κάμερα δεν υποστηρίζεται. Χρησιμοποιήστε τις Φωτογραφίες.'); setCameraOpen(true); return }; try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' }, width: { ideal: 1920 }, height: { ideal: 2560 } }, audio: false }); streamRef.current = stream; setCameraOpen(true); setTimeout(() => { if (videoRef.current) { videoRef.current.srcObject = stream; videoRef.current.play().catch(() => {}) } }, 0) } catch (cameraException) { setCameraError(cameraException?.message || 'Δεν ήταν δυνατή η πρόσβαση στην κάμερα.'); setCameraOpen(true) } }
  function chooseGallery() { galleryInputRef.current?.click() }
  function setImageFile(nextFile, requestCrop = true) { if (!nextFile) return; if (previewUrl) URL.revokeObjectURL(previewUrl); setFile(nextFile); setPreviewUrl(URL.createObjectURL(nextFile)); setItems([]); setOcrText(''); setError(''); setProgress(''); setNeedsCrop(requestCrop) }
  function handleGalleryFile(event) { const nextFile = event.target.files?.[0]; if (nextFile) { stopCamera(); setImageFile(nextFile, true) }; event.target.value = '' }
  function captureCamera() { const video = videoRef.current; if (!video || !video.videoWidth || !video.videoHeight) { setCameraError('Η κάμερα δεν είναι ακόμη έτοιμη.'); return }; const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height); canvas.toBlob((blob) => { if (!blob) { setCameraError('Δεν ήταν δυνατή η λήψη.'); return }; stopCamera(); setImageFile(new File([blob], 'camera-scan.jpg', { type: 'image/jpeg' }), true) }, 'image/jpeg', 0.95) }
  async function runOcr() { if (!file) return; setBusy(true); setError(''); setProgress('Προετοιμασία εγγράφου…'); try { const prepared = await prepareImage(file); setProgress('Ανάγνωση του πίνακα σπουδαστών…'); const worker = await createWorker('ell', 1, { logger: (message) => { if (message.status) setProgress(`${message.status} ${Math.round((message.progress || 0) * 100)}%`) } }); await worker.setParameters({ tessedit_pageseg_mode: '6', preserve_interword_spaces: '1' }); const result = await worker.recognize(prepared); const text = result.data.text || ''; const lines = result.data.lines?.map((line) => line.text).filter(Boolean) || text.split(/\r?\n/); const parsed = parseOcrLines(lines); setOcrText(text); setItems(parsed); await worker.terminate(); setProgress(parsed.length ? `Η ανάγνωση ολοκληρώθηκε: ${parsed.length} γραμμές εντοπίστηκαν. Ελέγξτε και διορθώστε πριν την καταχώριση.` : 'Δεν εντοπίστηκε αξιόπιστη γραμμή ΑΜ + ονοματεπώνυμο. Κάντε crop ώστε να μείνει μόνο ο πίνακας και δοκιμάστε ξανά.') } catch (ocrError) { setError(ocrError?.message || 'Αποτυχία OCR'); setProgress('') } finally { setBusy(false) } }
  function updateItem(index, key, value) { setItems((current) => current.map((item, itemIndex) => { if (itemIndex !== index) return item; const next = { ...item, [key]: value }; if (key === 'lastName' || key === 'firstName') next.fullName = `${next.lastName || ''} ${next.firstName || ''}`.trim(); return next })) }
  function isExisting(item) { const normalized = String(item.registryNumber || '').replace(/\D/g, ''); return normalized && existingRows.some((row) => String(registryColumn ? row[registryColumn] : valueFor(row, ['registry_number', 'registration_number', 'registry_no', 'am', 'student_number'])).replace(/\D/g, '') === normalized) }
  function buildRow(item) { const row = {}; if (registryColumn) row[registryColumn] = item.registryNumber.trim(); if (nameColumn) row[nameColumn] = `${item.lastName || ''} ${item.firstName || ''}`.trim(); if (lastNameColumn) row[lastNameColumn] = item.lastName.trim(); if (firstNameColumn) row[firstNameColumn] = item.firstName.trim(); return row }
  const scannerOverlay = { position: 'relative', width: '100%', maxWidth: 620, margin: '0 auto', aspectRatio: '3 / 4', overflow: 'hidden', borderRadius: 18, background: '#05070a', boxShadow: '0 12px 32px rgba(0,0,0,0.22)' }
  return <section className="data-card" style={{ padding: '1rem', marginBottom: '1rem' }}><input ref={galleryInputRef} type="file" accept="image/*" onChange={handleGalleryFile} style={{ display: 'none' }} /><div className="page-title-row"><div><p className="kicker">Εισαγωγή από έντυπο ISO</p><h2>📷 Σκανάρισμα παρουσιολογίου</h2><p>Κάμερα ή φωτογραφία → 1. crop 4 γωνιών → 2. πραγματικό ίσιωμα/crop → 3. OCR → έλεγχος → καταχώριση.</p></div></div>
    {!cameraOpen && !previewUrl && <div style={{ ...scannerOverlay, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1.2rem', boxSizing: 'border-box' }}><div style={{ textAlign: 'center', color: '#fff' }}><div style={{ fontSize: '3.2rem' }}>📄</div><h3>Σαρωτής παρουσιολογίου</h3><p style={{ color: '#d8dee8' }}>Κάμερα ή φωτογραφία από το iPhone.</p><button type="button" className="primary-button" onClick={openCamera}>📷 Άνοιγμα κάμερας</button><div style={{ marginTop: '0.7rem' }}><button type="button" className="secondary-button" onClick={chooseGallery}>🖼️ Επιλογή από Φωτογραφίες</button></div></div></div>}
    {cameraOpen && <div style={scannerOverlay}><video ref={videoRef} autoPlay playsInline muted style={{ width: '100%', height: '100%', objectFit: 'cover', display: cameraError ? 'none' : 'block' }} />{cameraError && <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem', color: '#fff', textAlign: 'center' }}>{cameraError}</div>}{!cameraError && <><div style={{ position: 'absolute', left: '7%', right: '7%', top: '4%', bottom: '18%', border: '2px solid #fff', borderRadius: 12, pointerEvents: 'none', boxShadow: '0 0 0 9999px rgba(0,0,0,0.18)' }} /><div style={{ position: 'absolute', left: '9%', right: '9%', top: '6%', textAlign: 'center', color: '#fff', textShadow: '0 1px 4px #000', fontSize: '0.8rem', fontWeight: 600 }}>Ολόκληρο το έντυπο μέσα στο πλαίσιο</div></>}<div style={{ position: 'absolute', left: 0, right: 0, bottom: 0, padding: '0.85rem 1rem', display: 'grid', gridTemplateColumns: '1fr auto 1fr', alignItems: 'center', background: 'linear-gradient(transparent,rgba(0,0,0,0.78))' }}><button type="button" onClick={chooseGallery} aria-label="Επιλογή φωτογραφίας" style={{ justifySelf: 'start', width: 62, height: 62, borderRadius: 14, border: '2px solid #fff', background: 'rgba(255,255,255,0.18)', color: '#fff', fontSize: '1.55rem' }}>🖼️</button><button type="button" onClick={captureCamera} disabled={Boolean(cameraError)} aria-label="Λήψη φωτογραφίας" style={{ width: 76, height: 76, borderRadius: '50%', border: '5px solid #fff', background: '#fff', color: '#17233b', fontSize: '1.6rem' }}>●</button><button type="button" onClick={stopCamera} aria-label="Κλείσιμο κάμερας" style={{ justifySelf: 'end', width: 62, height: 62, borderRadius: 14, border: '2px solid #fff', background: 'rgba(255,255,255,0.18)', color: '#fff', fontSize: '1.4rem' }}>✕</button></div><div style={{ position: 'absolute', left: 0, right: 0, bottom: 6, textAlign: 'center', color: '#fff', fontSize: '0.72rem', pointerEvents: 'none' }}>Φωτογραφίες</div></div>}
    {!cameraOpen && previewUrl && needsCrop && <CropEditor file={file} onApply={(cropped) => setImageFile(cropped, false)} onSkip={() => setNeedsCrop(false)} onBack={() => { setNeedsCrop(false); setFile(null); setPreviewUrl('') }} />}
    {!cameraOpen && previewUrl && !needsCrop && <div><div className="audit-note" style={{ marginBottom: '0.7rem' }}>✅ <strong>2. Το έγγραφο κόπηκε και ισιώθηκε.</strong> Αυτή είναι πλέον η νέα εικόνα που θα σταλεί στο OCR.</div><img src={previewUrl} alt="Κομμένο και ισιωμένο παρουσιολόγιο" style={{ width: '100%', maxHeight: 520, objectFit: 'contain', borderRadius: 10, border: '1px solid #d8dee8' }} /><div style={{ display: 'flex', gap: '0.65rem', marginTop: '0.8rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={() => setNeedsCrop(true)}>✂️ Ξανά 4 γωνίες</button><button type="button" className="secondary-button" onClick={() => { setFile(null); setPreviewUrl(''); setNeedsCrop(false) }}>🗑️ Απόρριψη</button><button type="button" className="primary-button" onClick={runOcr} disabled={busy}>{busy ? '⏳ Ανάγνωση…' : '🔎 3. Στείλε για OCR'}</button></div></div>}
    {progress && <div className="audit-note" style={{ marginTop: '0.8rem' }}>{progress}</div>}{error && <div className="error-box" style={{ marginTop: '0.8rem' }}>{error}</div>}
    {items.length > 0 && <div style={{ marginTop: '1rem' }}><div className="page-title-row"><div><h3>Έλεγχος πριν την καταχώριση</h3><p>Διορθώστε ελεύθερα κάθε γραμμή. 🟡 σημαίνει ότι το ΑΜ υπάρχει ήδη.</p></div><span className="count-badge">{items.length} γραμμές</span></div><div className="table-wrap"><table><thead><tr><th>ΑΜ</th><th>Επώνυμο</th><th>Όνομα</th><th>Κατάσταση</th></tr></thead><tbody>{items.map((item, index) => <tr key={`${item.registryNumber}-${index}`}><td><input value={item.registryNumber} onChange={(event) => updateItem(index, 'registryNumber', event.target.value)} /></td><td><input value={item.lastName} onChange={(event) => updateItem(index, 'lastName', event.target.value)} /></td><td><input value={item.firstName} onChange={(event) => updateItem(index, 'firstName', event.target.value)} /></td><td>{isExisting(item) ? '🟡 Ήδη υπάρχει' : '🟢 Νέα εγγραφή'}</td></tr>)}</tbody></table></div><div style={{ display: 'flex', gap: '0.65rem', justifyContent: 'flex-end', marginTop: '0.8rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={onClose}>Ακύρωση</button><button type="button" className="primary-button" onClick={() => onImport(items.filter((item) => !isExisting(item)).map(buildRow))}>💾 Καταχώριση νέων</button></div></div>}
    {ocrText && <details style={{ marginTop: '0.8rem' }}><summary>Τεχνική προεπισκόπηση OCR</summary><pre style={{ whiteSpace: 'pre-wrap', fontSize: '0.78rem' }}>{ocrText}</pre></details>}
  </section>
}

export default function StudentsView() {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [showOcr, setShowOcr] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('')
  async function loadStudents() { if (!supabase) return; setLoading(true); setError(''); const { data, error: queryError } = await supabase.from('students').select('*').limit(500); if (queryError) setError(queryError.message); else setRows(data ?? []); setLoading(false) }
  useEffect(() => { loadStudents() }, [])
  const columns = useMemo(() => { const keys = new Set(); rows.forEach((row) => Object.keys(row).forEach((key) => keys.add(key))); return [...keys] }, [rows])
  const filteredRows = useMemo(() => { const term = search.trim().toLowerCase(); if (!term) return rows; return rows.filter((row) => Object.values(row).some((value) => String(value ?? '').toLowerCase().includes(term))) }, [rows, search])
  async function saveStudent(draft) { setBusy(true); setError(''); setNotice(''); const payload = { ...draft }; SYSTEM_KEYS.forEach((key) => delete payload[key]); const operation = editing?.id ? supabase.from('students').update(payload).eq('id', editing.id).select('*').single() : supabase.from('students').insert(payload).select('*').single(); const { data, error: saveError } = await operation; if (saveError) setError(saveError.message); else { setRows((current) => editing?.id ? current.map((row) => row.id === editing.id ? data : row) : [data, ...current]); setNotice(editing?.id ? 'Ο σπουδαστής ενημερώθηκε.' : 'Ο σπουδαστής καταχωρίστηκε.'); setEditing(null); setShowForm(false) } setBusy(false) }
  async function deleteStudent(row) { if (!window.confirm(`Να διαγραφεί ο σπουδαστής ${String(valueFor(row, ['full_name', 'name', 'student_name']) || row.id)};\n\nΗ ενέργεια θα καταγραφεί στο ιστορικό ενεργειών.`)) return; setBusy(true); setError(''); setNotice(''); const { error: deleteError } = await supabase.from('students').delete().eq('id', row.id); if (deleteError) setError(deleteError.message); else { setRows((current) => current.filter((item) => item.id !== row.id)); setNotice('Ο σπουδαστής διαγράφηκε.') } setBusy(false) }
  async function importStudents(newRows) { if (!newRows.length) { setNotice('Δεν βρέθηκαν νέες εγγραφές για καταχώριση.'); return } setBusy(true); setError(''); setNotice(''); const { data, error: importError } = await supabase.from('students').insert(newRows).select('*'); if (importError) setError(importError.message); else { setRows((current) => [...(data || []), ...current]); setNotice(`${data?.length || 0} νέοι σπουδαστές καταχωρίστηκαν.`); setShowOcr(false) } setBusy(false) }
  return <section className="module-page"><div className="page-title-row"><div><p className="kicker">Μητρώο</p><h1>👥 Σπουδαστές</h1><p>Διαχείριση σπουδαστών με πραγματικά δεδομένα από τη βάση.</p></div><div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}><button className="primary-button" type="button" onClick={() => { setEditing(null); setShowForm(true); setShowOcr(false) }}>➕ Νέος σπουδαστής</button><button className="secondary-button" type="button" onClick={() => { setShowOcr((value) => !value); setShowForm(false) }}>📷 Σκανάρισμα / Φωτογραφία</button><button className="secondary-button" type="button" onClick={loadStudents}>↻ Ανανέωση</button></div></div>{notice && <div className="audit-note" style={{ marginBottom: '0.8rem' }}>{notice}</div>}{error && <div className="error-box" style={{ marginBottom: '0.8rem' }}>{error}</div>}{showForm && <StudentForm row={editing} columns={columns} onCancel={() => { setShowForm(false); setEditing(null) }} onSave={saveStudent} busy={busy} />}{showOcr && <OcrImport existingRows={rows} columns={columns} onImport={importStudents} onClose={() => setShowOcr(false)} />}{isSupabaseConfigured && <><div className="data-card" style={{ padding: '1rem', marginBottom: '1rem' }}><label>Αναζήτηση<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ΑΜ, ονοματεπώνυμο ή άλλο στοιχείο…" /></label></div><div className="data-card"><div className="page-title-row"><div><h2>Κατάλογος σπουδαστών</h2><p>{loading ? 'Φόρτωση…' : `Εμφανίζονται ${filteredRows.length} από ${rows.length} εγγραφές.`}</p></div><span className="count-badge">{rows.length}</span></div>{!loading && filteredRows.length === 0 ? <div className="empty-state"><div className="empty-icon">👥</div><h3>Δεν υπάρχουν εγγραφές</h3><p>Χρησιμοποιήστε «Σκανάρισμα / Φωτογραφία» ή «Νέος σπουδαστής» για εισαγωγή.</p></div> : <div className="table-wrap"><table><thead><tr>{columns.filter((column) => !SYSTEM_KEYS.has(column)).map((column) => <th key={column}>{labelFor(column)}</th>)}<th>Ενέργειες</th></tr></thead><tbody>{filteredRows.map((row) => <tr key={row.id}>{columns.filter((column) => !SYSTEM_KEYS.has(column)).map((column) => <td key={column}>{String(row[column] ?? '')}</td>)}<td><div style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap' }}><button className="secondary-button" type="button" onClick={() => { setEditing(row); setShowForm(true); setShowOcr(false) }}>✏️</button><button className="secondary-button" type="button" onClick={() => deleteStudent(row)} disabled={busy}>🗑️</button></div></td></tr>)}</tbody></table></div>}</div></>}{!isSupabaseConfigured && <div className="notice">Ρυθμίστε πρώτα τα environment variables του Supabase.</div>}</section>
}