import { useEffect, useMemo, useRef, useState } from 'react'
import { createWorker } from 'tesseract.js'
import { isSupabaseConfigured, supabase } from './lib/supabaseClient'

const SYSTEM_KEYS = new Set(['id', 'created_at', 'updated_at', 'deleted_at'])
const LABELS = { registry_number: 'Αριθμός Μητρώου', registration_number: 'Αριθμός Μητρώου', registry_no: 'Αριθμός Μητρώου', am: 'Αριθμός Μητρώου', student_number: 'Αριθμός Μητρώου', last_name: 'Επώνυμο', surname: 'Επώνυμο', first_name: 'Όνομα', name: 'Όνομα', full_name: 'Ονοματεπώνυμο', phone: 'Τηλέφωνο', semester: 'Εξάμηνο', group: 'Ομάδα', status: 'Κατάσταση' }
function labelFor(key) { return LABELS[key] || key.replaceAll('_', ' ') }
function valueFor(row, aliases) { const key = Object.keys(row || {}).find((candidate) => aliases.includes(candidate)); return key ? row[key] : '' }

function StudentForm({ row, columns, onCancel, onSave, busy }) {
  const editableColumns = columns.filter((column) => !SYSTEM_KEYS.has(column)); const [draft, setDraft] = useState(() => ({ ...(row || {}) })); useEffect(() => setDraft({ ...(row || {}) }), [row])
  return <form className="data-card" onSubmit={(event) => { event.preventDefault(); onSave(draft) }} style={{ padding: '1rem', marginBottom: '1rem' }}><div className="page-title-row"><div><p className="kicker">{row?.id ? 'Επεξεργασία' : 'Νέα εγγραφή'}</p><h2>{row?.id ? '✏️ Διόρθωση σπουδαστή' : '➕ Νέος σπουδαστής'}</h2><p>Όλα τα διαθέσιμα στοιχεία παραμένουν διορθώσιμα πριν την αποθήκευση.</p></div></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: '0.85rem' }}>{editableColumns.map((column) => <label key={column}>{labelFor(column)}<input value={draft[column] == null ? '' : String(draft[column])} onChange={(event) => setDraft((current) => ({ ...current, [column]: event.target.value }))} /></label>)}</div><div style={{ display: 'flex', gap: '0.65rem', justifyContent: 'flex-end', marginTop: '1rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={onCancel}>Ακύρωση</button><button type="submit" className="primary-button" disabled={busy}>{busy ? 'Αποθήκευση…' : 'Αποθήκευση'}</button></div></form>
}

function normalizeOcrLine(value) { return String(value || '').replace(/[|¦]/g, ' ').replace(/\s+/g, ' ').trim() }
function normalizeRegistryToken(token) { return String(token || '').toUpperCase().replace(/[ΟO]/g, '0').replace(/[ΙIÎ]/g, '1').replace(/[ΖZ]/g, '2').replace(/[ΕE]/g, '3').replace(/[ΑA]/g, '4').replace(/[SΣ]/g, '5').replace(/[GΓ]/g, '6').replace(/[ΤT]/g, '7').replace(/[ΒB]/g, '8').replace(/[qQ]/g, '9').replace(/\D/g, '') }
function cleanName(value) { return normalizeOcrLine(value).replace(/^[\s:;,.\-–—_/\\]+/, '').replace(/\s+/g, ' ').trim() }
function parseOcrLines(lines) {
  const results = []; const seen = new Set(); const blocked = /(ΗΜΕΡ|ΠΑΡΟΥΣ|ΣΠΟΥΔΑΣΤ|ΟΝΟΜΑΤΕΠΩΝ|ΕΠΩΝΥΜ|ΗΜΕΡΟΜΗΝ|ΥΠΟΓΡΑΦ|ΣΧΟΛΗ|ΤΜΗΜΑ|ΕΞΑΜΗΝΟ)/iu
  for (const rawLine of lines) { const line = normalizeOcrLine(rawLine); if (!line || blocked.test(line)) continue; const candidates = [...line.matchAll(/(?:^|\s)([0-9ΟOIΙΖZΕEAΑSΣGΓΤTΒBqQ]{4,8})(?=\s|$)/g)]; let selected = null; for (const candidate of candidates) { const registryNumber = normalizeRegistryToken(candidate[1]); if (registryNumber.length >= 4 && registryNumber.length <= 6) { selected = { candidate, registryNumber }; break } } if (!selected || seen.has(selected.registryNumber)) continue; let fullName = cleanName(line.slice(selected.candidate.index + selected.candidate[0].length)); if (!fullName || !/[A-ZΑ-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]/u.test(fullName)) continue; const parts = fullName.split(/\s+/).filter(Boolean); if (parts.length < 2) continue; if (fullName.length > 100) fullName = fullName.slice(0, 100).trim(); seen.add(selected.registryNumber); results.push({ registryNumber: selected.registryNumber, fullName, lastName: parts[0] || '', firstName: parts.slice(1).join(' ') }) }
  return results
}

async function prepareImage(file) { const bitmap = await createImageBitmap(file); const maxWidth = 2400; const scale = Math.min(1, maxWidth / bitmap.width); const width = Math.max(1, Math.round(bitmap.width * scale)); const height = Math.max(1, Math.round(bitmap.height * scale)); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const context = canvas.getContext('2d', { willReadFrequently: true }); context.drawImage(bitmap, 0, 0, width, height); const image = context.getImageData(0, 0, width, height); const data = image.data; for (let i = 0; i < data.length; i += 4) { const luminance = data[i] * 0.299 + data[i + 1] * 0.587 + data[i + 2] * 0.114; const contrast = Math.max(0, Math.min(255, ((luminance - 128) * 1.35) + 128)); data[i] = contrast; data[i + 1] = contrast; data[i + 2] = contrast }; context.putImageData(image, 0, 0); const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.95)); bitmap.close?.(); if (!blob) throw new Error('Δεν ήταν δυνατή η προετοιμασία της εικόνας.'); return new File([blob], 'attendance-document-ocr.jpg', { type: 'image/jpeg' }) }

function CropEditor({ file, onApply, onSkip, onBack }) {
  const [imageUrl, setImageUrl] = useState(''); const [box, setBox] = useState({ left: 6, top: 5, width: 88, height: 88 }); const areaRef = useRef(null); const dragRef = useRef(null)
  useEffect(() => { const url = URL.createObjectURL(file); setImageUrl(url); return () => URL.revokeObjectURL(url) }, [file])
  function pointerDown(event, mode) { event.preventDefault(); event.currentTarget.setPointerCapture?.(event.pointerId); dragRef.current = { mode, x: event.clientX, y: event.clientY, box: { ...box }, rect: areaRef.current?.getBoundingClientRect() } }
  function pointerMove(event) { const drag = dragRef.current; if (!drag?.rect) return; const dx = ((event.clientX - drag.x) / drag.rect.width) * 100; const dy = ((event.clientY - drag.y) / drag.rect.height) * 100; const b = drag.box; let next = { ...b }; if (drag.mode === 'move') { next.left = Math.max(0, Math.min(100 - b.width, b.left + dx)); next.top = Math.max(0, Math.min(100 - b.height, b.top + dy)) }; if (drag.mode === 'nw') { next.left = Math.max(0, Math.min(b.left + b.width - 12, b.left + dx)); next.top = Math.max(0, Math.min(b.top + b.height - 12, b.top + dy)); next.width = b.width + b.left - next.left; next.height = b.height + b.top - next.top }; if (drag.mode === 'ne') { next.top = Math.max(0, Math.min(b.top + b.height - 12, b.top + dy)); next.width = Math.max(12, Math.min(100 - b.left, b.width + dx)); next.height = b.height + b.top - next.top }; if (drag.mode === 'sw') { next.left = Math.max(0, Math.min(b.left + b.width - 12, b.left + dx)); next.width = b.width + b.left - next.left; next.height = Math.max(12, Math.min(100 - b.top, b.height + dy)) }; if (drag.mode === 'se') { next.width = Math.max(12, Math.min(100 - b.left, b.width + dx)); next.height = Math.max(12, Math.min(100 - b.top, b.height + dy)) }; setBox(next) }
  function pointerUp() { dragRef.current = null }
  async function applyCrop() { const bitmap = await createImageBitmap(file); const canvas = document.createElement('canvas'); const sx = Math.round(bitmap.width * box.left / 100); const sy = Math.round(bitmap.height * box.top / 100); const sw = Math.max(1, Math.round(bitmap.width * box.width / 100)); const sh = Math.max(1, Math.round(bitmap.height * box.height / 100)); canvas.width = sw; canvas.height = sh; canvas.getContext('2d').drawImage(bitmap, sx, sy, sw, sh, 0, 0, sw, sh); const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.96)); bitmap.close?.(); if (blob) onApply(new File([blob], 'attendance-cropped.jpg', { type: 'image/jpeg' })) }
  return <div style={{ marginTop: '0.8rem' }}><div className="audit-note">✂️ <strong>Περικοπή εγγράφου</strong> — σύρετε το πλαίσιο και τις 4 γωνίες ώστε να μείνει μόνο η περιοχή που θέλετε να διαβάσει το OCR.</div><div ref={areaRef} style={{ position: 'relative', marginTop: '0.7rem', width: '100%', overflow: 'hidden', borderRadius: 14, background: '#111' }}><img src={imageUrl} alt="Προεπισκόπηση για crop" style={{ display: 'block', width: '100%', height: 'auto', userSelect: 'none', pointerEvents: 'none' }} />{imageUrl && <div style={{ position: 'absolute', left: `${box.left}%`, top: `${box.top}%`, width: `${box.width}%`, height: `${box.height}%`, border: '2px solid #fff', boxSizing: 'border-box', boxShadow: '0 0 0 9999px rgba(0,0,0,0.48)', touchAction: 'none', cursor: 'move' }} onPointerDown={(event) => pointerDown(event, 'move')} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}>{[['nw','left','top'],['ne','right','top'],['sw','left','bottom'],['se','right','bottom']].map(([mode, h, v]) => <span key={mode} onPointerDown={(event) => { event.stopPropagation(); pointerDown(event, mode) }} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} style={{ position: 'absolute', [h]: -9, [v]: -9, width: 18, height: 18, borderRadius: '50%', background: '#fff', border: '2px solid #17233b', boxSizing: 'border-box', touchAction: 'none' }} />)}</div>}</div><div style={{ display: 'flex', gap: '0.6rem', justifyContent: 'space-between', marginTop: '0.8rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={onBack}>↩️ Πίσω</button><div style={{ display: 'flex', gap: '0.6rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={onSkip}>Χωρίς crop</button><button type="button" className="primary-button" onClick={applyCrop}>✂️ Χρήση επιλεγμένης περιοχής</button></div></div></div>
}

function OcrImport({ existingRows, columns, onImport, onClose }) {
  const [file, setFile] = useState(null); const [previewUrl, setPreviewUrl] = useState(''); const [ocrText, setOcrText] = useState(''); const [items, setItems] = useState([]); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(''); const [error, setError] = useState(''); const [cameraOpen, setCameraOpen] = useState(false); const [cameraError, setCameraError] = useState(''); const [needsCrop, setNeedsCrop] = useState(false)
  const videoRef = useRef(null); const streamRef = useRef(null); const galleryInputRef = useRef(null)
  useEffect(() => () => { if (previewUrl) URL.revokeObjectURL(previewUrl); if (streamRef.current) streamRef.current.getTracks().forEach((track) => track.stop()) }, [previewUrl])
  const registryColumn = columns.find((key) => ['registry_number', 'registration_number', 'registry_no', 'am', 'student_number', 'arithmos_mitroou'].includes(key)); const nameColumn = columns.find((key) => ['full_name', 'name', 'student_name', 'onomateponymo'].includes(key)); const lastNameColumn = columns.find((key) => ['last_name', 'surname', 'eponymo'].includes(key)); const firstNameColumn = columns.find((key) => ['first_name', 'onoma'].includes(key))
  function stopCamera() { if (streamRef.current) { streamRef.current.getTracks().forEach((track) => track.stop()); streamRef.current = null }; if (videoRef.current) videoRef.current.srcObject = null; setCameraOpen(false) }
  async function openCamera() { setCameraError(''); if (!navigator.mediaDevices?.getUserMedia) { setCameraError('Η κάμερα δεν υποστηρίζεται. Χρησιμοποιήστε τις Φωτογραφίες.'); setCameraOpen(true); return }; try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' }, width: { ideal: 1920 }, height: { ideal: 2560 } }, audio: false }); streamRef.current = stream; setCameraOpen(true); setTimeout(() => { if (videoRef.current) { videoRef.current.srcObject = stream; videoRef.current.play().catch(() => {}) } }, 0) } catch (cameraException) { setCameraError(cameraException?.message || 'Δεν ήταν δυνατή η πρόσβαση στην κάμερα.'); setCameraOpen(true) } }
  function chooseGallery() { galleryInputRef.current?.click() }
  function setImageFile(nextFile) { if (!nextFile) return; if (previewUrl) URL.revokeObjectURL(previewUrl); setFile(nextFile); setPreviewUrl(URL.createObjectURL(nextFile)); setItems([]); setOcrText(''); setError(''); setProgress(''); setNeedsCrop(true) }
  function handleGalleryFile(event) { const nextFile = event.target.files?.[0]; if (nextFile) { stopCamera(); setImageFile(nextFile) }; event.target.value = '' }
  function captureCamera() { const video = videoRef.current; if (!video || !video.videoWidth || !video.videoHeight) { setCameraError('Η κάμερα δεν είναι ακόμη έτοιμη.'); return }; const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height); canvas.toBlob((blob) => { if (!blob) { setCameraError('Δεν ήταν δυνατή η λήψη.'); return }; stopCamera(); setImageFile(new File([blob], 'camera-scan.jpg', { type: 'image/jpeg' })) }, 'image/jpeg', 0.95) }
  async function runOcr() { if (!file) return; setBusy(true); setError(''); setProgress('Προετοιμασία εγγράφου…'); try { const prepared = await prepareImage(file); setProgress('Ανάγνωση του πίνακα σπουδαστών…'); const worker = await createWorker('ell', 1, { logger: (message) => { if (message.status) setProgress(`${message.status} ${Math.round((message.progress || 0) * 100)}%`) } }); await worker.setParameters({ tessedit_pageseg_mode: '6', preserve_interword_spaces: '1' }); const result = await worker.recognize(prepared); const text = result.data.text || ''; const lines = result.data.lines?.map((line) => line.text).filter(Boolean) || text.split(/\r?\n/); const parsed = parseOcrLines(lines); setOcrText(text); setItems(parsed); await worker.terminate(); setProgress(parsed.length ? `Η ανάγνωση ολοκληρώθηκε: ${parsed.length} γραμμές εντοπίστηκαν. Ελέγξτε και διορθώστε πριν την καταχώριση.` : 'Δεν εντοπίστηκε αξιόπιστη γραμμή ΑΜ + ονοματεπώνυμο. Κάντε crop ώστε να μείνει μόνο ο πίνακας και δοκιμάστε ξανά.') } catch (ocrError) { setError(ocrError?.message || 'Αποτυχία OCR'); setProgress('') } finally { setBusy(false) } }
  function updateItem(index, key, value) { setItems((current) => current.map((item, itemIndex) => { if (itemIndex !== index) return item; const next = { ...item, [key]: value }; if (key === 'lastName' || key === 'firstName') next.fullName = `${next.lastName || ''} ${next.firstName || ''}`.trim(); return next })) }
  function isExisting(item) { const normalized = String(item.registryNumber || '').replace(/\D/g, ''); return normalized && existingRows.some((row) => String(registryColumn ? row[registryColumn] : valueFor(row, ['registry_number', 'registration_number', 'registry_no', 'am', 'student_number'])).replace(/\D/g, '') === normalized) }
  function buildRow(item) { const row = {}; if (registryColumn) row[registryColumn] = item.registryNumber.trim(); if (nameColumn) row[nameColumn] = `${item.lastName || ''} ${item.firstName || ''}`.trim(); if (lastNameColumn) row[lastNameColumn] = item.lastName.trim(); if (firstNameColumn) row[firstNameColumn] = item.firstName.trim(); return row }
  const scannerOverlay = { position: 'relative', width: '100%', maxWidth: 620, margin: '0 auto', aspectRatio: '3 / 4', overflow: 'hidden', borderRadius: 18, background: '#05070a', boxShadow: '0 12px 32px rgba(0,0,0,0.22)' }
  return <section className="data-card" style={{ padding: '1rem', marginBottom: '1rem' }}><input ref={galleryInputRef} type="file" accept="image/*" onChange={handleGalleryFile} style={{ display: 'none' }} /><div className="page-title-row"><div><p className="kicker">Εισαγωγή από έντυπο ISO</p><h2>📷 Σκανάρισμα παρουσιολογίου</h2><p>Κάμερα ή φωτογραφία → crop της σωστής περιοχής → OCR → έλεγχος → καταχώριση.</p></div></div>
    {!cameraOpen && !previewUrl && <div style={{ ...scannerOverlay, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1.2rem', boxSizing: 'border-box' }}><div style={{ textAlign: 'center', color: '#fff' }}><div style={{ fontSize: '3.2rem' }}>📄</div><h3>Σαρωτής παρουσιολογίου</h3><p style={{ color: '#d8dee8' }}>Κάμερα ή φωτογραφία από το iPhone.</p><button type="button" className="primary-button" onClick={openCamera}>📷 Άνοιγμα κάμερας</button><div style={{ marginTop: '0.7rem' }}><button type="button" className="secondary-button" onClick={chooseGallery}>🖼️ Επιλογή από Φωτογραφίες</button></div></div></div>}
    {cameraOpen && <div style={scannerOverlay}><video ref={videoRef} autoPlay playsInline muted style={{ width: '100%', height: '100%', objectFit: 'cover', display: cameraError ? 'none' : 'block' }} />{cameraError && <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem', color: '#fff', textAlign: 'center' }}>{cameraError}</div>}{!cameraError && <><div style={{ position: 'absolute', left: '7%', right: '7%', top: '4%', bottom: '18%', border: '2px solid #fff', borderRadius: 12, pointerEvents: 'none', boxShadow: '0 0 0 9999px rgba(0,0,0,0.18)' }} /><div style={{ position: 'absolute', left: '9%', right: '9%', top: '6%', textAlign: 'center', color: '#fff', textShadow: '0 1px 4px #000', fontSize: '0.8rem', fontWeight: 600 }}>Ολόκληρο το έντυπο μέσα στο πλαίσιο</div></>}<div style={{ position: 'absolute', left: 0, right: 0, bottom: 0, padding: '0.85rem 1rem', display: 'grid', gridTemplateColumns: '1fr auto 1fr', alignItems: 'center', background: 'linear-gradient(transparent,rgba(0,0,0,0.78))' }}><button type="button" onClick={chooseGallery} aria-label="Επιλογή φωτογραφίας" style={{ justifySelf: 'start', width: 62, height: 62, borderRadius: 14, border: '2px solid #fff', background: 'rgba(255,255,255,0.18)', color: '#fff', fontSize: '1.55rem' }}>🖼️</button><button type="button" onClick={captureCamera} disabled={Boolean(cameraError)} aria-label="Λήψη φωτογραφίας" style={{ width: 76, height: 76, borderRadius: '50%', border: '5px solid #fff', background: '#fff', color: '#17233b', fontSize: '1.6rem' }}>●</button><button type="button" onClick={stopCamera} aria-label="Κλείσιμο κάμερας" style={{ justifySelf: 'end', width: 62, height: 62, borderRadius: 14, border: '2px solid #fff', background: 'rgba(255,255,255,0.18)', color: '#fff', fontSize: '1.4rem' }}>✕</button></div><div style={{ position: 'absolute', left: 0, right: 0, bottom: 6, textAlign: 'center', color: '#fff', fontSize: '0.72rem', pointerEvents: 'none' }}>Φωτογραφίες</div></div>}
    {!cameraOpen && previewUrl && needsCrop && <CropEditor file={file} onApply={(cropped) => { setNeedsCrop(false); setImageFile(cropped) }} onSkip={() => setNeedsCrop(false)} onBack={() => { setNeedsCrop(false); setFile(null); setPreviewUrl('') }} />}
    {!cameraOpen && previewUrl && !needsCrop && <div><img src={previewUrl} alt="Περικομμένο παρουσιολόγιο" style={{ width: '100%', maxHeight: 420, objectFit: 'contain', borderRadius: 10, border: '1px solid #d8dee8' }} /><div style={{ display: 'flex', gap: '0.65rem', marginTop: '0.8rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={() => setNeedsCrop(true)}>✂️ Νέο crop</button><button type="button" className="secondary-button" onClick={openCamera}>📷 Νέο σκανάρισμα</button><button type="button" className="secondary-button" onClick={chooseGallery}>🖼️ Άλλη φωτογραφία</button><button type="button" className="primary-button" onClick={runOcr} disabled={busy}>{busy ? '⏳ Ανάγνωση…' : '🔎 Ανάγνωση πίνακα'}</button></div></div>}
    {progress && <div className="audit-note" style={{ marginTop: '0.8rem' }}>{progress}</div>}{error && <div className="error-box" style={{ marginTop: '0.8rem' }}>{error}</div>}
    {items.length > 0 && <div style={{ marginTop: '1rem' }}><div className="page-title-row"><div><h3>Έλεγχος πριν την καταχώριση</h3><p>Διορθώστε ελεύθερα κάθε γραμμή. 🟡 σημαίνει ότι το ΑΜ υπάρχει ήδη.</p></div><span className="count-badge">{items.length} γραμμές</span></div><div className="table-wrap"><table><thead><tr><th>ΑΜ</th><th>Επώνυμο</th><th>Όνομα</th><th>Κατάσταση</th></tr></thead><tbody>{items.map((item, index) => <tr key={`${item.registryNumber}-${index}`}><td><input value={item.registryNumber} onChange={(event) => updateItem(index, 'registryNumber', event.target.value)} /></td><td><input value={item.lastName} onChange={(event) => updateItem(index, 'lastName', event.target.value)} /></td><td><input value={item.firstName} onChange={(event) => updateItem(index, 'firstName', event.target.value)} /></td><td>{isExisting(item) ? '🟡 Ήδη υπάρχει' : '🟢 Νέα εγγραφή'}</td></tr>)}</tbody></table></div><div style={{ display: 'flex', gap: '0.65rem', justifyContent: 'flex-end', marginTop: '0.8rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={onClose}>Ακύρωση</button><button type="button" className="primary-button" onClick={() => onImport(items.filter((item) => !isExisting(item)).map(buildRow))}>💾 Καταχώριση νέων</button></div></div>}
    {ocrText && <details style={{ marginTop: '0.8rem' }}><summary>Τεχνική προεπισκόπηση OCR</summary><pre style={{ whiteSpace: 'pre-wrap', fontSize: '0.78rem' }}>{ocrText}</pre></details>}
  </section>
}

export default function StudentsView() {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [showOcr, setShowOcr] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('')
  async function loadStudents() { if (!supabase) return; setLoading(true); setError(''); const { data, error: queryError } = await supabase.from('students').select('*').limit(500); if (queryError) setError(queryError.message); else setRows(data ?? []); setLoading(false) }
  useEffect(() => { loadStudents() }, [])
  const columns = useMemo(() => { const keys = new Set(); rows.forEach((row) => Object.keys(row).forEach((key) => keys.add(key))); return [...keys] }, [rows])
  const filteredRows = useMemo(() => { const term = search.trim().toLowerCase(); if (!term) return rows; return rows.filter((row) => Object.values(row).some((value) => String(value ?? '').toLowerCase().includes(term))) }, [rows, search])
  async function saveStudent(draft) { setBusy(true); setError(''); setNotice(''); const payload = { ...draft }; SYSTEM_KEYS.forEach((key) => delete payload[key]); const operation = editing?.id ? supabase.from('students').update(payload).eq('id', editing.id).select('*').single() : supabase.from('students').insert(payload).select('*').single(); const { data, error: saveError } = await operation; if (saveError) setError(saveError.message); else { setRows((current) => editing?.id ? current.map((row) => row.id === editing.id ? data : row) : [data, ...current]); setNotice(editing?.id ? 'Ο σπουδαστής ενημερώθηκε.' : 'Ο σπουδαστής καταχωρίστηκε.'); setEditing(null); setShowForm(false) } setBusy(false) }
  async function deleteStudent(row) { if (!window.confirm(`Να διαγραφεί ο σπουδαστής ${String(valueFor(row, ['full_name', 'name', 'student_name']) || row.id)};\n\nΗ ενέργεια θα καταγραφεί στο ιστορικό ενεργειών.`)) return; setBusy(true); setError(''); setNotice(''); const { error: deleteError } = await supabase.from('students').delete().eq('id', row.id); if (deleteError) setError(deleteError.message); else { setRows((current) => current.filter((item) => item.id !== row.id)); setNotice('Ο σπουδαστής διαγράφηκε.') } setBusy(false) }
  async function importStudents(newRows) { if (!newRows.length) { setNotice('Δεν βρέθηκαν νέες εγγραφές για καταχώριση.'); return } setBusy(true); setError(''); setNotice(''); const { data, error: importError } = await supabase.from('students').insert(newRows).select('*'); if (importError) setError(importError.message); else { setRows((current) => [...(data || []), ...current]); setNotice(`${data?.length || 0} νέοι σπουδαστές καταχωρίστηκαν.`); setShowOcr(false) } setBusy(false) }
  return <section className="module-page"><div className="page-title-row"><div><p className="kicker">Μητρώο</p><h1>👥 Σπουδαστές</h1><p>Διαχείριση σπουδαστών με πραγματικά δεδομένα από τη βάση.</p></div><div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}><button className="primary-button" type="button" onClick={() => { setEditing(null); setShowForm(true); setShowOcr(false) }}>➕ Νέος σπουδαστής</button><button className="secondary-button" type="button" onClick={() => { setShowOcr((value) => !value); setShowForm(false) }}>📷 Σκανάρισμα / Φωτογραφία</button><button className="secondary-button" type="button" onClick={loadStudents}>↻ Ανανέωση</button></div></div>{notice && <div className="audit-note" style={{ marginBottom: '0.8rem' }}>{notice}</div>}{error && <div className="error-box" style={{ marginBottom: '0.8rem' }}>{error}</div>}{showForm && <StudentForm row={editing} columns={columns} onCancel={() => { setShowForm(false); setEditing(null) }} onSave={saveStudent} busy={busy} />}{showOcr && <OcrImport existingRows={rows} columns={columns} onImport={importStudents} onClose={() => setShowOcr(false)} />}{isSupabaseConfigured && <><div className="data-card" style={{ padding: '1rem', marginBottom: '1rem' }}><label>Αναζήτηση<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ΑΜ, ονοματεπώνυμο ή άλλο στοιχείο…" /></label></div><div className="data-card"><div className="page-title-row"><div><h2>Κατάλογος σπουδαστών</h2><p>{loading ? 'Φόρτωση…' : `Εμφανίζονται ${filteredRows.length} από ${rows.length} εγγραφές.`}</p></div><span className="count-badge">{rows.length}</span></div>{!loading && filteredRows.length === 0 ? <div className="empty-state"><div className="empty-icon">👥</div><h3>Δεν υπάρχουν εγγραφές</h3><p>Χρησιμοποιήστε «Σκανάρισμα / Φωτογραφία» ή «Νέος σπουδαστής» για εισαγωγή.</p></div> : <div className="table-wrap"><table><thead><tr>{columns.filter((column) => !SYSTEM_KEYS.has(column)).map((column) => <th key={column}>{labelFor(column)}</th>)}<th>Ενέργειες</th></tr></thead><tbody>{filteredRows.map((row) => <tr key={row.id}>{columns.filter((column) => !SYSTEM_KEYS.has(column)).map((column) => <td key={column}>{String(row[column] ?? '')}</td>)}<td><div style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap' }}><button className="secondary-button" type="button" onClick={() => { setEditing(row); setShowForm(true); setShowOcr(false) }}>✏️</button><button className="secondary-button" type="button" onClick={() => deleteStudent(row)} disabled={busy}>🗑️</button></div></td></tr>)}</tbody></table></div>}</div></>}{!isSupabaseConfigured && <div className="notice">Ρυθμίστε πρώτα τα environment variables του Supabase.</div>}</section>
}
