import { useEffect, useMemo, useRef, useState } from 'react'
import { createWorker } from 'tesseract.js'
import { isSupabaseConfigured, supabase } from './lib/supabaseClient'

const SYSTEM_KEYS = new Set(['id', 'created_at', 'updated_at', 'deleted_at'])
const LABELS = {
  registry_number: 'Αριθμός Μητρώου', registration_number: 'Αριθμός Μητρώου', registry_no: 'Αριθμός Μητρώου', am: 'Αριθμός Μητρώου', student_number: 'Αριθμός Μητρώου',
  last_name: 'Επώνυμο', surname: 'Επώνυμο', first_name: 'Όνομα', name: 'Όνομα', full_name: 'Ονοματεπώνυμο', phone: 'Τηλέφωνο', semester: 'Εξάμηνο', group: 'Ομάδα', status: 'Κατάσταση',
}
function labelFor(key) { return LABELS[key] || key.replaceAll('_', ' ') }
function valueFor(row, aliases) { const key = Object.keys(row || {}).find((candidate) => aliases.includes(candidate)); return key ? row[key] : '' }
function StudentForm({ row, columns, onCancel, onSave, busy }) {
  const editableColumns = columns.filter((column) => !SYSTEM_KEYS.has(column)); const [draft, setDraft] = useState(() => ({ ...(row || {}) }))
  useEffect(() => setDraft({ ...(row || {}) }), [row])
  function setValue(key, value) { setDraft((current) => ({ ...current, [key]: value })) }
  return <form className="data-card" onSubmit={(event) => { event.preventDefault(); onSave(draft) }} style={{ padding: '1rem', marginBottom: '1rem' }}><div className="page-title-row"><div><p className="kicker">{row?.id ? 'Επεξεργασία' : 'Νέα εγγραφή'}</p><h2>{row?.id ? '✏️ Διόρθωση σπουδαστή' : '➕ Νέος σπουδαστής'}</h2><p>Όλα τα διαθέσιμα στοιχεία παραμένουν διορθώσιμα πριν την αποθήκευση.</p></div></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: '0.85rem' }}>{editableColumns.map((column) => <label key={column}>{labelFor(column)}<input value={draft[column] == null ? '' : String(draft[column])} onChange={(event) => setValue(column, event.target.value)} /></label>)}</div><div style={{ display: 'flex', gap: '0.65rem', justifyContent: 'flex-end', marginTop: '1rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={onCancel}>Ακύρωση</button><button type="submit" className="primary-button" disabled={busy}>{busy ? 'Αποθήκευση…' : 'Αποθήκευση'}</button></div></form>
}
function parseOcrText(text) {
  const results = []; const seen = new Set()
  for (const rawLine of text.split(/\r?\n/)) { const line = rawLine.replace(/[|]/g, ' ').replace(/\s+/g, ' ').trim(); if (!line) continue; const match = line.match(/^(?:\d{1,3}\s+)?(\d{4,6})\s+(.{3,})$/u); if (!match) continue; const registryNumber = match[1]; let fullName = match[2].trim(); fullName = fullName.replace(/\s+(?:Π|P|Α|A)\s*$/i, '').trim(); if (seen.has(registryNumber)) continue; seen.add(registryNumber); const parts = fullName.split(/\s+/); results.push({ registryNumber, fullName, lastName: parts[0] || '', firstName: parts.slice(1).join(' ') }) }
  return results
}
function OcrImport({ existingRows, columns, onImport, onClose }) {
  const [file, setFile] = useState(null); const [previewUrl, setPreviewUrl] = useState(''); const [ocrText, setOcrText] = useState(''); const [items, setItems] = useState([]); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(''); const [error, setError] = useState(''); const [cameraOpen, setCameraOpen] = useState(false); const [cameraError, setCameraError] = useState('')
  const videoRef = useRef(null); const streamRef = useRef(null); const galleryInputRef = useRef(null)
  useEffect(() => () => { if (previewUrl) URL.revokeObjectURL(previewUrl); if (streamRef.current) streamRef.current.getTracks().forEach((track) => track.stop()) }, [previewUrl])
  const registryColumn = columns.find((key) => ['registry_number', 'registration_number', 'registry_no', 'am', 'student_number', 'arithmos_mitroou'].includes(key)); const nameColumn = columns.find((key) => ['full_name', 'name', 'student_name', 'onomateponymo'].includes(key)); const lastNameColumn = columns.find((key) => ['last_name', 'surname', 'eponymo'].includes(key)); const firstNameColumn = columns.find((key) => ['first_name', 'onoma'].includes(key))
  function stopCamera() { if (streamRef.current) { streamRef.current.getTracks().forEach((track) => track.stop()); streamRef.current = null }; if (videoRef.current) videoRef.current.srcObject = null; setCameraOpen(false) }
  async function openCamera() {
    setCameraError('')
    if (!navigator.mediaDevices?.getUserMedia) { setCameraError('Η κάμερα δεν υποστηρίζεται σε αυτό το πρόγραμμα περιήγησης. Χρησιμοποιήστε τις Φωτογραφίες.'); setCameraOpen(true); return }
    try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); streamRef.current = stream; setCameraOpen(true); setTimeout(() => { if (videoRef.current) { videoRef.current.srcObject = stream; videoRef.current.play().catch(() => {}) } }, 0) } catch (cameraException) { setCameraError(cameraException?.message || 'Δεν ήταν δυνατή η πρόσβαση στην κάμερα.'); setCameraOpen(true) }
  }
  function chooseGallery() { galleryInputRef.current?.click() }
  function setImageFile(nextFile) { if (!nextFile) return; setFile(nextFile); setPreviewUrl(URL.createObjectURL(nextFile)); setItems([]); setOcrText(''); setError(''); setProgress('') }
  function handleGalleryFile(event) { const nextFile = event.target.files?.[0]; if (nextFile) { stopCamera(); setImageFile(nextFile) }; event.target.value = '' }
  function captureCamera() {
    const video = videoRef.current; if (!video || !video.videoWidth || !video.videoHeight) { setCameraError('Η κάμερα δεν είναι ακόμη έτοιμη.'); return }
    const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; const context = canvas.getContext('2d'); context.drawImage(video, 0, 0, canvas.width, canvas.height)
    canvas.toBlob((blob) => { if (!blob) { setCameraError('Δεν ήταν δυνατή η λήψη της εικόνας.'); return }; stopCamera(); setImageFile(new File([blob], 'camera-scan.jpg', { type: 'image/jpeg' })) }, 'image/jpeg', 0.92)
  }
  async function runOcr() { if (!file) return; setBusy(true); setError(''); setProgress('Προετοιμασία OCR…'); try { const worker = await createWorker('ell', 1, { logger: (message) => { if (message.status) setProgress(`${message.status} ${Math.round((message.progress || 0) * 100)}%`) } }); const result = await worker.recognize(file); const text = result.data.text || ''; setOcrText(text); setItems(parseOcrText(text)); await worker.terminate(); setProgress('Η αναγνώριση ολοκληρώθηκε. Ελέγξτε και διορθώστε τα στοιχεία πριν την καταχώριση.') } catch (ocrError) { setError(ocrError?.message || 'Αποτυχία OCR'); setProgress('') } finally { setBusy(false) } }
  function updateItem(index, key, value) { setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item)) }
  function isExisting(item) { const normalized = String(item.registryNumber || '').replace(/\D/g, ''); return existingRows.some((row) => String(registryColumn ? row[registryColumn] : valueFor(row, ['registry_number', 'registration_number', 'registry_no', 'am', 'student_number'])).replace(/\D/g, '') === normalized) }
  function buildRow(item) { const row = {}; if (registryColumn) row[registryColumn] = item.registryNumber.trim(); if (nameColumn) row[nameColumn] = item.fullName.trim(); if (lastNameColumn) row[lastNameColumn] = item.lastName.trim(); if (firstNameColumn) row[firstNameColumn] = item.firstName.trim(); return row }
  const scannerOverlay = { position: 'relative', width: '100%', maxWidth: 620, margin: '0 auto', aspectRatio: '3 / 4', overflow: 'hidden', borderRadius: 18, background: '#05070a', boxShadow: '0 12px 32px rgba(0,0,0,0.22)' }
  return <section className="data-card" style={{ padding: '1rem', marginBottom: '1rem' }}><input ref={galleryInputRef} type="file" accept="image/*" onChange={handleGalleryFile} style={{ display: 'none' }} />
    <div className="page-title-row"><div><p className="kicker">Εισαγωγή από έντυπο ISO</p><h2>📷 Σκανάρισμα παρουσιολογίου</h2><p>Χρησιμοποιήστε την κάμερα ή επιλέξτε φωτογραφία από τις Φωτογραφίες του iPhone. Και οι δύο επιλογές οδηγούν στο ίδιο OCR.</p></div></div>
    {!cameraOpen && !previewUrl && <div style={{ ...scannerOverlay, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1.2rem', boxSizing: 'border-box' }}><div style={{ textAlign: 'center', color: '#fff' }}><div style={{ fontSize: '3.2rem', marginBottom: '0.6rem' }}>📷</div><h3 style={{ margin: '0 0 0.45rem' }}>Σαρωτής παρουσιολογίου</h3><p style={{ margin: '0 0 1.2rem', color: '#d8dee8' }}>Ανοίξτε την κάμερα για σκανάρισμα ή επιλέξτε μια υπάρχουσα φωτογραφία.</p><button type="button" className="primary-button" onClick={openCamera}>📷 Άνοιγμα κάμερας</button></div></div>}
    {cameraOpen && <div style={scannerOverlay}><video ref={videoRef} autoPlay playsInline muted style={{ width: '100%', height: '100%', objectFit: 'cover', display: cameraError ? 'none' : 'block' }} />{cameraError && <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1.2rem', color: '#fff', textAlign: 'center' }}><div><div style={{ fontSize: '2.5rem' }}>⚠️</div><p>{cameraError}</p></div></div>} {!cameraError && <div style={{ position: 'absolute', left: '12%', right: '12%', top: '10%', bottom: '17%', border: '2px solid rgba(255,255,255,0.85)', borderRadius: 12, pointerEvents: 'none' }} />}<div style={{ position: 'absolute', left: 0, right: 0, bottom: 0, padding: '0.85rem 1rem', display: 'grid', gridTemplateColumns: '1fr auto 1fr', alignItems: 'center', background: 'linear-gradient(transparent,rgba(0,0,0,0.78))' }}><button type="button" onClick={chooseGallery} aria-label="Επιλογή φωτογραφίας" style={{ justifySelf: 'start', width: 62, height: 62, borderRadius: 14, border: '2px solid #fff', background: 'rgba(255,255,255,0.18)', color: '#fff', fontSize: '1.55rem' }}>🖼️</button><button type="button" onClick={captureCamera} aria-label="Λήψη φωτογραφίας" disabled={Boolean(cameraError)} style={{ width: 76, height: 76, borderRadius: '50%', border: '5px solid #fff', background: '#fff', color: '#17233b', fontSize: '1.6rem', boxShadow: '0 2px 12px rgba(0,0,0,0.35)' }}>●</button><button type="button" onClick={stopCamera} aria-label="Κλείσιμο κάμερας" style={{ justifySelf: 'end', width: 62, height: 62, borderRadius: 14, border: '2px solid #fff', background: 'rgba(255,255,255,0.18)', color: '#fff', fontSize: '1.4rem' }}>✕</button></div><div style={{ position: 'absolute', left: 0, right: 0, bottom: 6, textAlign: 'center', color: '#fff', fontSize: '0.72rem', pointerEvents: 'none' }}>Φωτογραφίες</div></div>}
    {!cameraOpen && previewUrl && <div><img src={previewUrl} alt="Προεπισκόπηση εντύπου ISO" style={{ width: '100%', maxHeight: 420, objectFit: 'contain', border: '1px solid #d8dee8', borderRadius: 10, background: '#f7f8fa' }} /><div style={{ display: 'flex', gap: '0.65rem', marginTop: '0.8rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={openCamera}>📷 Νέο σκανάρισμα</button><button type="button" className="secondary-button" onClick={chooseGallery}>🖼️ Άλλη φωτογραφία</button><button type="button" className="primary-button" onClick={runOcr} disabled={busy}>{busy ? '⏳ Ανάγνωση…' : '🔎 Ανάγνωση με OCR'}</button></div></div>}
    {!cameraOpen && !previewUrl && <div style={{ display: 'flex', justifyContent: 'center', marginTop: '0.8rem' }}><button type="button" className="secondary-button" onClick={chooseGallery}>🖼️ Επιλογή από Φωτογραφίες</button></div>}
    {progress && <div className="audit-note" style={{ marginTop: '0.8rem' }}>{progress}</div>}{error && <div className="error-box" style={{ marginTop: '0.8rem' }}>{error}</div>}
    {items.length > 0 && <div style={{ marginTop: '1rem' }}><div className="page-title-row"><div><h3>Έλεγχος πριν την καταχώριση</h3><p>Διορθώστε ελεύθερα κάθε γραμμή. 🟡 σημαίνει ότι το ΑΜ υπάρχει ήδη.</p></div><span className="count-badge">{items.length} γραμμές</span></div><div className="table-wrap"><table><thead><tr><th>ΑΜ</th><th>Επώνυμο</th><th>Όνομα</th><th>Κατάσταση</th></tr></thead><tbody>{items.map((item, index) => <tr key={`${item.registryNumber}-${index}`}><td><input value={item.registryNumber} onChange={(event) => updateItem(index, 'registryNumber', event.target.value)} /></td><td><input value={item.lastName} onChange={(event) => updateItem(index, 'lastName', event.target.value)} /></td><td><input value={item.firstName} onChange={(event) => updateItem(index, 'firstName', event.target.value)} /></td><td>{isExisting(item) ? '🟡 Ήδη υπάρχει' : '🟢 Νέα εγγραφή'}</td></tr>)}</tbody></table></div><div style={{ display: 'flex', gap: '0.65rem', justifyContent: 'flex-end', marginTop: '0.8rem', flexWrap: 'wrap' }}><button type="button" className="secondary-button" onClick={onClose}>Ακύρωση</button><button type="button" className="primary-button" onClick={() => onImport(items.filter((item) => !isExisting(item)).map(buildRow))}>💾 Καταχώριση νέων</button></div></div>}
    {ocrText && <details style={{ marginTop: '0.8rem' }}><summary>Τεχνική προεπισκόπηση OCR</summary><pre style={{ whiteSpace: 'pre-wrap', fontSize: '0.78rem' }}>{ocrText}</pre></details>}
  </section>
}
export default function StudentsView() {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [showOcr, setShowOcr] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('')
  async function loadStudents() { if (!supabase) return; setLoading(true); setError(''); const { data, error: queryError } = await supabase.from('students').select('*').limit(500); if (queryError) setError(queryError.message); else setRows(data ?? []); setLoading(false) }
  useEffect(() => { loadStudents() }, [])
  const columns = useMemo(() => { const keys = new Set(); rows.forEach((row) => Object.keys(row).forEach((key) => keys.add(key))); return [...keys] }, [rows])
  const filteredRows = useMemo(() => { const term = search.trim().toLowerCase(); if (!term) return rows; return rows.filter((row) => Object.values(row).some((value) => String(value ?? '').toLowerCase().includes(term))) }, [rows, search])
  async function saveStudent(draft) { setBusy(true); setError(''); setNotice(''); const payload = { ...draft }; SYSTEM_KEYS.forEach((key) => delete payload[key]); const operation = editing?.id ? supabase.from('students').update(payload).eq('id', editing.id).select('*').single() : supabase.from('students').insert(payload).select('*').single(); const { data, error: saveError } = await operation; if (saveError) setError(saveError.message); else { setRows((current) => editing?.id ? current.map((row) => row.id === editing.id ? data : row) : [data, ...current]); setNotice(editing?.id ? 'Ο σπουδαστής ενημερώθηκε.' : 'Ο σπουδαστής καταχωρίστηκε.'); setEditing(null); setShowForm(false) } setBusy(false) }
  async function deleteStudent(row) { if (!window.confirm(`Να διαγραφεί ο σπουδαστής ${String(valueFor(row, ['full_name', 'name', 'student_name']) || row.id)};\n\nΗ ενέργεια θα καταγραφεί στο ιστορικό ενεργειών.`)) return; setBusy(true); setError(''); setNotice(''); const { error: deleteError } = await supabase.from('students').delete().eq('id', row.id); if (deleteError) setError(deleteError.message); else { setRows((current) => current.filter((item) => item.id !== row.id)); setNotice('Ο σπουδαστής διαγράφηκε.') } setBusy(false) }
  async function importStudents(newRows) { if (!newRows.length) { setNotice('Δεν βρέθηκαν νέες εγγραφές για καταχώριση.'); return } setBusy(true); setError(''); setNotice(''); const { data, error: importError } = await supabase.from('students').insert(newRows).select('*'); if (importError) setError(importError.message); else { setRows((current) => [...(data || []), ...current]); setNotice(`${data?.length || 0} νέοι σπουδαστές καταχωρίστηκαν.`); setShowOcr(false) } setBusy(false) }
  return <section className="module-page"><div className="page-title-row"><div><p className="kicker">Μητρώο</p><h1>👥 Σπουδαστές</h1><p>Διαχείριση σπουδαστών με πραγματικά δεδομένα από τη βάση.</p></div><div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}><button className="primary-button" type="button" onClick={() => { setEditing(null); setShowForm(true); setShowOcr(false) }}>➕ Νέος σπουδαστής</button><button className="secondary-button" type="button" onClick={() => { setShowOcr((value) => !value); setShowForm(false) }}>📷 Σκανάρισμα / Φωτογραφία</button><button className="secondary-button" type="button" onClick={loadStudents}>↻ Ανανέωση</button></div></div>{notice && <div className="audit-note" style={{ marginBottom: '0.8rem' }}>{notice}</div>}{error && <div className="error-box" style={{ marginBottom: '0.8rem' }}>{error}</div>}{showForm && <StudentForm row={editing} columns={columns} onCancel={() => { setShowForm(false); setEditing(null) }} onSave={saveStudent} busy={busy} />}{showOcr && <OcrImport existingRows={rows} columns={columns} onImport={importStudents} onClose={() => setShowOcr(false)} />}{isSupabaseConfigured && <><div className="data-card" style={{ padding: '1rem', marginBottom: '1rem' }}><label>Αναζήτηση<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ΑΜ, ονοματεπώνυμο ή άλλο στοιχείο…" /></label></div><div className="data-card"><div className="page-title-row"><div><h2>Κατάλογος σπουδαστών</h2><p>{loading ? 'Φόρτωση…' : `Εμφανίζονται ${filteredRows.length} από ${rows.length} εγγραφές.`}</p></div><span className="count-badge">{rows.length}</span></div>{!loading && filteredRows.length === 0 ? <div className="empty-state"><div className="empty-icon">👥</div><h3>Δεν υπάρχουν εγγραφές</h3><p>Χρησιμοποιήστε «Σκανάρισμα / Φωτογραφία» ή «Νέος σπουδαστής» για εισαγωγή.</p></div> : <div className="table-wrap"><table><thead><tr>{columns.filter((column) => !SYSTEM_KEYS.has(column)).map((column) => <th key={column}>{labelFor(column)}</th>)}<th>Ενέργειες</th></tr></thead><tbody>{filteredRows.map((row) => <tr key={row.id}>{columns.filter((column) => !SYSTEM_KEYS.has(column)).map((column) => <td key={column}>{String(row[column] ?? '')}</td>)}<td><div style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap' }}><button className="secondary-button" type="button" onClick={() => { setEditing(row); setShowForm(true); setShowOcr(false) }}>✏️</button><button className="secondary-button" type="button" onClick={() => deleteStudent(row)} disabled={busy}>🗑️</button></div></td></tr>)}</tbody></table></div>}</div></>}{!isSupabaseConfigured && <div className="notice">Ρυθμίστε πρώτα τα environment variables του Supabase.</div>}</section>
}
